-- Roles and permissions, file 1 of 4: the ACCESS schema for organisations,
-- users and roles.
--
-- Run by hand as ACCOUNTADMIN in a Snowflake worksheet, before the other
-- three files. Safe to run twice: every CREATE uses IF NOT EXISTS, and
-- GRANT does nothing when the privilege is already there.
--
-- Like the ILR and BURROW schemas, ILR_APP_ROLE gets SELECT, INSERT and
-- UPDATE here but never DELETE. Users are deactivated and roles revoked by
-- setting a date, so there is always a record of who had access when.
--
-- Column names follow the ILR schema's style (no underscores, as in
-- OFFICERREFNUMBER), since these tables are joined to ILR all the time.
-- There are no foreign keys to other schemas. The app checks those links.
-- Allowed values are listed in column comments and enforced by the app,
-- because Snowflake has no CHECK constraints.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE capture_wh;

CREATE SCHEMA IF NOT EXISTS CAPTURE_DB.ACCESS
  COMMENT = 'Organisations, users and roles for Warren and Burrow.';

GRANT USAGE ON SCHEMA CAPTURE_DB.ACCESS TO ROLE ILR_APP_ROLE;

-- Set before the tables are created, so each new table gets these grants.
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA CAPTURE_DB.ACCESS TO ROLE ILR_APP_ROLE;


CREATE TABLE IF NOT EXISTS CAPTURE_DB.ACCESS.ORGANISATION (
  ORGANISATIONID     VARCHAR(20) NOT NULL COMMENT 'e.g. ORG-T001. Every learner, officer, employer and user belongs to exactly one organisation.',
  NAME               VARCHAR(200) NOT NULL,
  UKPRN              NUMBER(8,0) COMMENT 'The provider''s UK Provider Reference Number, when known.',
  ISTESTDATA         BOOLEAN DEFAULT FALSE NOT NULL COMMENT 'TRUE for dummy data, so it can all be found and removed before real use.',
  CREATEDAT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
  CONSTRAINT PK_ORGANISATION PRIMARY KEY (ORGANISATIONID)
)
COMMENT = 'Training providers. Nobody sees another organisation''s data.';


CREATE TABLE IF NOT EXISTS CAPTURE_DB.ACCESS.APP_USER (
  USERID             VARCHAR(36) NOT NULL COMMENT 'Generated by the app, or a fixed USR-T id for test users.',
  ORGANISATIONID     VARCHAR(20) NOT NULL,
  DISPLAYNAME        VARCHAR(200) NOT NULL,
  EMAIL              VARCHAR(320) NOT NULL COMMENT 'Unique. How real single sign-on will match a person to this user.',
  SSOSUBJECT         VARCHAR(255) COMMENT 'The identity provider''s id for this person, once single sign-on is added. Unique when set.',
  OFFICERREFNUMBER   VARCHAR(20) COMMENT 'For staff (tutor, assessor, IQA, manager): their ILR.OFFICER record.',
  LEARNREFNUMBER     VARCHAR(12) COMMENT 'For a learner: their ILR.LEARNER record.',
  EMPLOYERID         VARCHAR(20) COMMENT 'For an employer contact: their ILR.EMPLOYER record.',
  ISACTIVE           BOOLEAN DEFAULT TRUE NOT NULL COMMENT 'FALSE once deactivated. An inactive user cannot sign in.',
  DEACTIVATEDAT      TIMESTAMP_LTZ,
  DEACTIVATEDBY      VARCHAR(36) COMMENT 'USERID of the manager who deactivated them.',
  ISTESTDATA         BOOLEAN DEFAULT FALSE NOT NULL COMMENT 'TRUE for dummy data, so it can all be found and removed before real use.',
  CREATEDAT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
  CREATEDBY          VARCHAR(36),
  CONSTRAINT PK_APP_USER PRIMARY KEY (USERID),
  CONSTRAINT UQ_APP_USER_EMAIL UNIQUE (EMAIL),
  CONSTRAINT UQ_APP_USER_SSOSUBJECT UNIQUE (SSOSUBJECT),
  CONSTRAINT FK_APP_USER_ORGANISATION FOREIGN KEY (ORGANISATIONID) REFERENCES CAPTURE_DB.ACCESS.ORGANISATION (ORGANISATIONID)
)
COMMENT = 'People who can sign in. Never deleted - deactivated instead.';


CREATE TABLE IF NOT EXISTS CAPTURE_DB.ACCESS.USER_ROLE (
  ROLEGRANTID        VARCHAR(40) NOT NULL COMMENT 'Generated by the app, or a fixed RG-T id for test data.',
  USERID             VARCHAR(36) NOT NULL,
  ROLE               VARCHAR(10) NOT NULL COMMENT 'LEARNER | TUTOR | ASSESSOR | IQA | EMPLOYER | MANAGER',
  GRANTEDAT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
  GRANTEDBY          VARCHAR(40) NOT NULL COMMENT 'USERID of the manager who granted it, or test-data-seed.',
  REVOKEDAT          TIMESTAMP_LTZ COMMENT 'Set when the role is taken away. A role is active only while this is empty.',
  REVOKEDBY          VARCHAR(40),
  ISTESTDATA         BOOLEAN DEFAULT FALSE NOT NULL COMMENT 'TRUE for dummy data, so it can all be found and removed before real use.',
  CONSTRAINT PK_USER_ROLE PRIMARY KEY (ROLEGRANTID),
  CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (USERID) REFERENCES CAPTURE_DB.ACCESS.APP_USER (USERID)
)
COMMENT = 'The roles each user holds, one row per grant. A user can hold several. Revoked, never deleted.';


-- Stated explicitly too, so this doesn't rely on the future grants alone.
GRANT SELECT, INSERT, UPDATE ON TABLE CAPTURE_DB.ACCESS.ORGANISATION TO ROLE ILR_APP_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE CAPTURE_DB.ACCESS.APP_USER TO ROLE ILR_APP_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE CAPTURE_DB.ACCESS.USER_ROLE TO ROLE ILR_APP_ROLE;


-- Checks. Expected: the three tables listed, and for each one OWNERSHIP
-- for ACCOUNTADMIN plus SELECT, INSERT and UPDATE (and no DELETE) for ILR_APP_ROLE.
SHOW TABLES IN SCHEMA CAPTURE_DB.ACCESS;
SHOW GRANTS ON TABLE CAPTURE_DB.ACCESS.ORGANISATION;
SHOW GRANTS ON TABLE CAPTURE_DB.ACCESS.APP_USER;
SHOW GRANTS ON TABLE CAPTURE_DB.ACCESS.USER_ROLE;
