-- Roles and permissions, file 2 of 4: organisations on the ILR records,
-- caseload assignments with roles and end dates, employers, and test-data
-- flags.
--
-- Run by hand as ACCOUNTADMIN in a Snowflake worksheet, after file 1.
-- Safe to run twice: columns are added only if missing, backfills only fill
-- empty values, new rows are added only if not already there, and
-- GRANT and REVOKE do nothing when already applied.
--
-- What it changes:
--   1. ILR.LEARNER and ILR.OFFICER get ORGANISATIONID. All existing records
--      go into ORG-T001, Rarebit Test Provider.
--   2. ILR.LEARNER, ILR.OFFICER and ILR.LEARNING_DELIVERY get ISTESTDATA
--      (FALSE for now - file 4 marks the dummy records).
--   3. New ILR.OFFICER_ASSIGNMENT: which officer is a learner's tutor or
--      assessor, with a start and an end. Ending an assignment sets ENDEDAT
--      instead of deleting it, so caseload history is kept, and the same
--      officer can be assigned again later as a new row. The existing
--      ILR.LEARNER_OFFICER links are copied in. LEARNER_OFFICER itself is
--      left as it is but the app stops using it, and ILR_APP_ROLE loses
--      DELETE on it.
--   4. New ILR.EMPLOYER and ILR.LEARNER_EMPLOYER (with from and to dates).
--
-- Until the new server code is running, the app's existing "remove officer"
-- button will fail (it deletes from LEARNER_OFFICER), and officers assigned
-- in the app will only reach the old table. Best not to change caseloads in
-- the app until then.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE capture_wh;


-- ---------------------------------------------------------------------------
-- 1. The first organisation, and every existing record in it.
-- ---------------------------------------------------------------------------
MERGE INTO CAPTURE_DB.ACCESS.ORGANISATION t
USING (SELECT 'ORG-T001' AS ORGANISATIONID, 'Rarebit Test Provider' AS NAME) s
  ON t.ORGANISATIONID = s.ORGANISATIONID
WHEN NOT MATCHED THEN INSERT (ORGANISATIONID, NAME, ISTESTDATA) VALUES (s.ORGANISATIONID, s.NAME, TRUE);

ALTER TABLE CAPTURE_DB.ILR.LEARNER ADD COLUMN IF NOT EXISTS ORGANISATIONID VARCHAR(20)
  COMMENT 'The organisation this learner belongs to, as ACCESS.ORGANISATION.';
UPDATE CAPTURE_DB.ILR.LEARNER SET ORGANISATIONID = 'ORG-T001' WHERE ORGANISATIONID IS NULL;
ALTER TABLE CAPTURE_DB.ILR.LEARNER ALTER COLUMN ORGANISATIONID SET NOT NULL;

ALTER TABLE CAPTURE_DB.ILR.OFFICER ADD COLUMN IF NOT EXISTS ORGANISATIONID VARCHAR(20)
  COMMENT 'The organisation this officer belongs to, as ACCESS.ORGANISATION.';
UPDATE CAPTURE_DB.ILR.OFFICER SET ORGANISATIONID = 'ORG-T001' WHERE ORGANISATIONID IS NULL;
ALTER TABLE CAPTURE_DB.ILR.OFFICER ALTER COLUMN ORGANISATIONID SET NOT NULL;


-- ---------------------------------------------------------------------------
-- 2. Test-data flags. Existing rows are set to FALSE here. File 4 marks the
--    dummy records TRUE.
-- ---------------------------------------------------------------------------
ALTER TABLE CAPTURE_DB.ILR.LEARNER ADD COLUMN IF NOT EXISTS ISTESTDATA BOOLEAN DEFAULT FALSE
  COMMENT 'TRUE for dummy data, so it can all be found and removed before real use.';
UPDATE CAPTURE_DB.ILR.LEARNER SET ISTESTDATA = FALSE WHERE ISTESTDATA IS NULL;
ALTER TABLE CAPTURE_DB.ILR.LEARNER ALTER COLUMN ISTESTDATA SET NOT NULL;

ALTER TABLE CAPTURE_DB.ILR.OFFICER ADD COLUMN IF NOT EXISTS ISTESTDATA BOOLEAN DEFAULT FALSE
  COMMENT 'TRUE for dummy data, so it can all be found and removed before real use.';
UPDATE CAPTURE_DB.ILR.OFFICER SET ISTESTDATA = FALSE WHERE ISTESTDATA IS NULL;
ALTER TABLE CAPTURE_DB.ILR.OFFICER ALTER COLUMN ISTESTDATA SET NOT NULL;

ALTER TABLE CAPTURE_DB.ILR.LEARNING_DELIVERY ADD COLUMN IF NOT EXISTS ISTESTDATA BOOLEAN DEFAULT FALSE
  COMMENT 'TRUE for dummy data, so it can all be found and removed before real use.';
UPDATE CAPTURE_DB.ILR.LEARNING_DELIVERY SET ISTESTDATA = FALSE WHERE ISTESTDATA IS NULL;
ALTER TABLE CAPTURE_DB.ILR.LEARNING_DELIVERY ALTER COLUMN ISTESTDATA SET NOT NULL;


-- ---------------------------------------------------------------------------
-- 3. Caseload assignments, replacing ILR.LEARNER_OFFICER.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CAPTURE_DB.ILR.OFFICER_ASSIGNMENT (
  ASSIGNMENTID       VARCHAR(40) DEFAULT UUID_STRING() NOT NULL COMMENT 'Generated by the app, or a fixed ASG-T id for test data.',
  LEARNREFNUMBER     VARCHAR(12) NOT NULL,
  OFFICERREFNUMBER   VARCHAR(20) NOT NULL,
  ASSIGNMENTROLE     VARCHAR(10) NOT NULL COMMENT 'TUTOR | ASSESSOR - the officer''s role for this learner.',
  STARTEDAT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
  STARTEDBY          VARCHAR(40) NOT NULL COMMENT 'USERID of the manager who made the assignment, or how it was created.',
  ENDEDAT            TIMESTAMP_LTZ COMMENT 'Set when the assignment ends. An assignment is current only while this is empty.',
  ENDEDBY            VARCHAR(40),
  ISTESTDATA         BOOLEAN DEFAULT FALSE NOT NULL COMMENT 'TRUE for dummy data, so it can all be found and removed before real use.',
  CONSTRAINT PK_OFFICER_ASSIGNMENT PRIMARY KEY (ASSIGNMENTID),
  CONSTRAINT FK_OFFICER_ASSIGNMENT_LEARNER FOREIGN KEY (LEARNREFNUMBER) REFERENCES CAPTURE_DB.ILR.LEARNER (LEARNREFNUMBER),
  CONSTRAINT FK_OFFICER_ASSIGNMENT_OFFICER FOREIGN KEY (OFFICERREFNUMBER) REFERENCES CAPTURE_DB.ILR.OFFICER (OFFICERREFNUMBER)
)
COMMENT = 'Which officer is each learner''s tutor or assessor, and when. Ended, never deleted.';

-- Copy each existing link in once, with its role taken from the officer's type.
MERGE INTO CAPTURE_DB.ILR.OFFICER_ASSIGNMENT t
USING (
  SELECT lo.LEARNREFNUMBER, lo.OFFICERREFNUMBER, o.OFFICERTYPE AS ASSIGNMENTROLE
  FROM CAPTURE_DB.ILR.LEARNER_OFFICER lo
  JOIN CAPTURE_DB.ILR.OFFICER o ON o.OFFICERREFNUMBER = lo.OFFICERREFNUMBER
  WHERE o.OFFICERTYPE IN ('TUTOR', 'ASSESSOR')
) s
  ON t.LEARNREFNUMBER = s.LEARNREFNUMBER
 AND t.OFFICERREFNUMBER = s.OFFICERREFNUMBER
 AND t.ENDEDAT IS NULL
WHEN NOT MATCHED THEN INSERT (LEARNREFNUMBER, OFFICERREFNUMBER, ASSIGNMENTROLE, STARTEDBY)
  VALUES (s.LEARNREFNUMBER, s.OFFICERREFNUMBER, s.ASSIGNMENTROLE, 'copied from LEARNER_OFFICER');

GRANT SELECT, INSERT, UPDATE ON TABLE CAPTURE_DB.ILR.OFFICER_ASSIGNMENT TO ROLE ILR_APP_ROLE;

-- The app no longer deletes caseload links.
REVOKE DELETE ON TABLE CAPTURE_DB.ILR.LEARNER_OFFICER FROM ROLE ILR_APP_ROLE;


-- ---------------------------------------------------------------------------
-- 4. Employers, and which employer each learner works for.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CAPTURE_DB.ILR.EMPLOYER (
  EMPLOYERID         VARCHAR(20) NOT NULL COMMENT 'e.g. EMP-T001. One row per employer per organisation, so the same company at two providers is two rows.',
  ORGANISATIONID     VARCHAR(20) NOT NULL COMMENT 'The organisation whose employer record this is.',
  NAME               VARCHAR(200) NOT NULL,
  EMPLOYERREF        NUMBER(9,0) COMMENT 'The employer reference number used in the ILR (EmpId), when known. The same company has the same number at every provider.',
  ISTESTDATA         BOOLEAN DEFAULT FALSE NOT NULL COMMENT 'TRUE for dummy data, so it can all be found and removed before real use.',
  CREATEDAT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
  CONSTRAINT PK_EMPLOYER PRIMARY KEY (EMPLOYERID)
)
COMMENT = 'Employers of apprentices, per organisation.';

CREATE TABLE IF NOT EXISTS CAPTURE_DB.ILR.LEARNER_EMPLOYER (
  LEARNREFNUMBER     VARCHAR(12) NOT NULL,
  EMPLOYERID         VARCHAR(20) NOT NULL,
  FROMDATE           DATE NOT NULL COMMENT 'When the learner started with this employer.',
  TODATE             DATE COMMENT 'When they left. The link is current while this is empty or in the future.',
  ISTESTDATA         BOOLEAN DEFAULT FALSE NOT NULL COMMENT 'TRUE for dummy data, so it can all be found and removed before real use.',
  CREATEDAT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
  CONSTRAINT PK_LEARNER_EMPLOYER PRIMARY KEY (LEARNREFNUMBER, EMPLOYERID, FROMDATE),
  CONSTRAINT FK_LEARNER_EMPLOYER_LEARNER FOREIGN KEY (LEARNREFNUMBER) REFERENCES CAPTURE_DB.ILR.LEARNER (LEARNREFNUMBER),
  CONSTRAINT FK_LEARNER_EMPLOYER_EMPLOYER FOREIGN KEY (EMPLOYERID) REFERENCES CAPTURE_DB.ILR.EMPLOYER (EMPLOYERID)
)
COMMENT = 'Which employer each learner works for, and when. Ended with TODATE, never deleted.';

GRANT SELECT, INSERT, UPDATE ON TABLE CAPTURE_DB.ILR.EMPLOYER TO ROLE ILR_APP_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE CAPTURE_DB.ILR.LEARNER_EMPLOYER TO ROLE ILR_APP_ROLE;


-- ---------------------------------------------------------------------------
-- Checks.
-- ---------------------------------------------------------------------------
-- Expected: 13 learners and 3 officers, all in ORG-T001, none marked as test data yet.
SELECT 'LEARNER' AS TABLE_NAME, ORGANISATIONID, ISTESTDATA, COUNT(*) AS ROWS_FOUND FROM CAPTURE_DB.ILR.LEARNER GROUP BY 1, 2, 3
UNION ALL
SELECT 'OFFICER', ORGANISATIONID, ISTESTDATA, COUNT(*) FROM CAPTURE_DB.ILR.OFFICER GROUP BY 1, 2, 3
UNION ALL
SELECT 'LEARNING_DELIVERY', NULL, ISTESTDATA, COUNT(*) FROM CAPTURE_DB.ILR.LEARNING_DELIVERY GROUP BY 1, 2, 3;

-- Expected: the 2 existing links (OFF0001 as ASSESSOR for TESTL0002 and TESTL0013), both current.
SELECT LEARNREFNUMBER, OFFICERREFNUMBER, ASSIGNMENTROLE, STARTEDBY, ENDEDAT
FROM CAPTURE_DB.ILR.OFFICER_ASSIGNMENT
ORDER BY LEARNREFNUMBER;

-- Expected: OWNERSHIP for ACCOUNTADMIN plus INSERT, SELECT and UPDATE for ILR_APP_ROLE - no DELETE.
SHOW GRANTS ON TABLE CAPTURE_DB.ILR.LEARNER_OFFICER;

-- Expected: OWNERSHIP for ACCOUNTADMIN plus INSERT, SELECT and UPDATE for ILR_APP_ROLE on each.
SHOW GRANTS ON TABLE CAPTURE_DB.ILR.OFFICER_ASSIGNMENT;
SHOW GRANTS ON TABLE CAPTURE_DB.ILR.EMPLOYER;
SHOW GRANTS ON TABLE CAPTURE_DB.ILR.LEARNER_EMPLOYER;
