-- Roles and permissions, file 3 of 4: Burrow tables for employer witness
-- confirmations and IQA checks.
--
-- Run by hand as ACCOUNTADMIN in a Snowflake worksheet, after files 1 and 2.
-- Safe to run twice: CREATE TABLE IF NOT EXISTS leaves existing tables
-- alone, and REVOKE does nothing if already applied.
--
-- Both tables are add-only records, like EVIDENCE_REVIEW: the schema's
-- future grants give ILR_APP_ROLE SELECT, INSERT and UPDATE on new tables,
-- and this script takes UPDATE back, so a confirmation or a check can never
-- be changed afterwards. Column names follow the BURROW schema's style.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE capture_wh;

CREATE TABLE IF NOT EXISTS CAPTURE_DB.BURROW.WITNESS_CONFIRMATION (
  CONFIRMATION_ID    VARCHAR(36) DEFAULT UUID_STRING() NOT NULL COMMENT 'Generated by the app.',
  EVIDENCE_ID        VARCHAR(36) NOT NULL COMMENT 'A witness statement, as BURROW.EVIDENCE.',
  SUBMISSION_NUMBER  NUMBER(5,0) NOT NULL COMMENT 'Which submission of the evidence was confirmed (EVIDENCE.SUBMISSION_COUNT at the time).',
  EMPLOYERID         VARCHAR(20) NOT NULL COMMENT 'The employer confirming, as ILR.EMPLOYER.',
  CONFIRMED_BY       VARCHAR(36) NOT NULL COMMENT 'USERID of the employer contact, as ACCESS.APP_USER.',
  CONFIRMER_NAME     VARCHAR(200) NOT NULL COMMENT 'Their name at the time, kept in case the user record changes.',
  OUTCOME            VARCHAR(10) NOT NULL COMMENT 'confirmed | declined',
  COMMENT_TEXT       VARCHAR(2000) COMMENT 'Anything the employer wants to add.',
  CONFIRMED_AT       TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
  CONSTRAINT PK_WITNESS_CONFIRMATION PRIMARY KEY (CONFIRMATION_ID),
  CONSTRAINT FK_WITNESS_CONFIRMATION_EVIDENCE FOREIGN KEY (EVIDENCE_ID) REFERENCES CAPTURE_DB.BURROW.EVIDENCE (EVIDENCE_ID)
)
COMMENT = 'Employers confirming (or declining) witness statements for their own apprentices. Add-only: never updated or deleted.';

CREATE TABLE IF NOT EXISTS CAPTURE_DB.BURROW.IQA_CHECK (
  CHECK_ID                   VARCHAR(36) DEFAULT UUID_STRING() NOT NULL COMMENT 'Generated by the app.',
  EVIDENCE_ID                VARCHAR(36) NOT NULL,
  REVIEW_ID                  VARCHAR(36) NOT NULL COMMENT 'The assessor''s sign-off being checked, as BURROW.EVIDENCE_REVIEW.',
  ASSESSOR_OFFICERREFNUMBER  VARCHAR(20) NOT NULL COMMENT 'Who made that sign-off, copied from the review. The app refuses a check when this is the IQA''s own officer reference.',
  IQA_USERID                 VARCHAR(36) NOT NULL COMMENT 'The IQA doing the check, as ACCESS.APP_USER.',
  IQA_OFFICERREFNUMBER       VARCHAR(20) NOT NULL COMMENT 'The IQA''s officer reference at the time.',
  IQA_NAME                   VARCHAR(200) NOT NULL COMMENT 'Their name at the time, kept in case the user record changes.',
  OUTCOME                    VARCHAR(20) NOT NULL COMMENT 'agreed | action_required',
  FEEDBACK                   VARCHAR(2000) COMMENT 'What the IQA found, and any action for the assessor.',
  CHECKED_AT                 TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
  CONSTRAINT PK_IQA_CHECK PRIMARY KEY (CHECK_ID),
  CONSTRAINT FK_IQA_CHECK_EVIDENCE FOREIGN KEY (EVIDENCE_ID) REFERENCES CAPTURE_DB.BURROW.EVIDENCE (EVIDENCE_ID),
  CONSTRAINT FK_IQA_CHECK_REVIEW FOREIGN KEY (REVIEW_ID) REFERENCES CAPTURE_DB.BURROW.EVIDENCE_REVIEW (REVIEW_ID)
)
COMMENT = 'Internal quality assurance checks of assessor sign-offs. Nobody checks their own. Add-only: never updated or deleted.';

-- Make both add-only for the app. SELECT and INSERT stay.
REVOKE UPDATE ON TABLE CAPTURE_DB.BURROW.WITNESS_CONFIRMATION FROM ROLE ILR_APP_ROLE;
REVOKE UPDATE ON TABLE CAPTURE_DB.BURROW.IQA_CHECK FROM ROLE ILR_APP_ROLE;

-- Checks. Expected for each: OWNERSHIP for ACCOUNTADMIN plus INSERT and
-- SELECT for ILR_APP_ROLE - no UPDATE and no DELETE.
SHOW GRANTS ON TABLE CAPTURE_DB.BURROW.WITNESS_CONFIRMATION;
SHOW GRANTS ON TABLE CAPTURE_DB.BURROW.IQA_CHECK;
