-- Burrow evidence tables in CAPTURE_DB.BURROW.
--
-- Run by hand as ACCOUNTADMIN in a Snowflake worksheet. Safe to run twice:
-- every table uses CREATE TABLE IF NOT EXISTS, and the REVOKE at the end
-- does nothing if it has already been applied.
--
-- ILR_APP_ROLE gets SELECT, INSERT and UPDATE on these tables through the
-- schema's future grants, but never DELETE: evidence is part of a learner's
-- official record, so nothing is ever deleted. Where the app needs to
-- "remove" something (a draft's file, a KSB claim, a whole piece of
-- evidence) it marks the row instead - see the *_AT / *_BY columns below.
--
-- Constraints: Snowflake records primary and foreign keys but does not
-- enforce them, and has no CHECK constraints, so the allowed values listed
-- in the column comments are enforced by the app. Keys are declared anyway
-- as documentation and for tools. There are deliberately no foreign keys to
-- other schemas:
--   - learners (LEARNREFNUMBER) and officers (OFFICERREFNUMBER) are the same
--     references the ILR schema uses, joined on by value
--   - KSBs are linked by ST reference + KSB reference (e.g. ST0072 + K1),
--     not by a database link, so evidence works with sample KSBs now and
--     the real ones from CAPTURE_DB.SKILLS.KSB later.
--
-- IDs are UUIDs generated by the app (crypto.randomUUID()) so it knows a new
-- row's ID without reading it back. UUID_STRING() is only a fallback.
-- Timestamps are TIMESTAMP_LTZ, as in the LARS and SKILLS import tables.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE capture_wh;


-- ---------------------------------------------------------------------------
-- EVIDENCE: one row per piece of evidence.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CAPTURE_DB.BURROW.EVIDENCE (
  EVIDENCE_ID        VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
  LEARNREFNUMBER     VARCHAR(12) NOT NULL COMMENT 'The learner, as ILR.LEARNER.LEARNREFNUMBER.',
  STDCODE            NUMBER(5,0) NOT NULL COMMENT 'LARS standard code of the learner''s programme when the evidence was created, as ILR.LEARNING_DELIVERY.STDCODE.',
  ST_REFERENCE       VARCHAR(10) NOT NULL COMMENT 'ST reference of that standard (e.g. ST0072). KSB claims are made against this.',
  TITLE              VARCHAR(200) NOT NULL,
  EVIDENCE_TYPE      VARCHAR(30) NOT NULL COMMENT 'observation | witness_statement | work_product | professional_discussion | project | reflective_account | other',
  OCCURRED_ON        DATE NOT NULL COMMENT 'The date the activity happened, which can be before the evidence was added.',
  REFLECTION         VARCHAR COMMENT 'The learner''s reflection on what they did and learned.',
  STATUS             VARCHAR(20) DEFAULT 'draft' NOT NULL COMMENT 'draft | submitted | changes_requested | signed_off | withdrawn',
  SUBMISSION_COUNT   NUMBER(5,0) DEFAULT 0 NOT NULL COMMENT 'How many times it has been submitted. Each review records which submission it looked at.',
  CREATED_AT         TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
  CREATED_BY         VARCHAR(100) NOT NULL COMMENT 'Who added it: a learner reference or an officer reference.',
  UPDATED_AT         TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL COMMENT 'Last change of any kind, including status changes.',
  UPDATED_BY         VARCHAR(100),
  SUBMITTED_AT       TIMESTAMP_LTZ COMMENT 'The most recent submission. Earlier ones are in EVIDENCE_REVIEW.',
  SIGNED_OFF_AT      TIMESTAMP_LTZ,
  SIGNED_OFF_BY      VARCHAR(20) COMMENT 'OFFICERREFNUMBER of the assessor who signed it off.',
  WITHDRAWN_AT       TIMESTAMP_LTZ,
  WITHDRAWN_BY       VARCHAR(100),
  WITHDRAWN_REASON   VARCHAR(500),
  CONSTRAINT PK_EVIDENCE PRIMARY KEY (EVIDENCE_ID)
)
COMMENT = 'Burrow e-portfolio: one row per piece of evidence. Never deleted - withdrawn instead (STATUS = withdrawn).';


-- ---------------------------------------------------------------------------
-- EVIDENCE_REVIEW: every review an assessor makes, appended, never changed.
-- Created before EVIDENCE_KSB, which refers to it.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CAPTURE_DB.BURROW.EVIDENCE_REVIEW (
  REVIEW_ID          VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
  EVIDENCE_ID        VARCHAR(36) NOT NULL,
  SUBMISSION_NUMBER  NUMBER(5,0) NOT NULL COMMENT 'Which submission this reviewed (EVIDENCE.SUBMISSION_COUNT at the time).',
  OFFICERREFNUMBER   VARCHAR(20) NOT NULL COMMENT 'The reviewing assessor, as ILR.OFFICER.OFFICERREFNUMBER.',
  OFFICER_NAME       VARCHAR(160) NOT NULL COMMENT 'The assessor''s name at the time, kept in case the officer record changes.',
  REVIEWED_AT        TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
  OUTCOME            VARCHAR(20) NOT NULL COMMENT 'signed_off | changes_requested',
  FEEDBACK           VARCHAR COMMENT 'The assessor''s feedback to the learner.',
  KSB_DECISIONS      VARIANT NOT NULL COMMENT 'Every claimed KSB''s decision in this review: [{ksb_type, ksb_reference, decision (confirmed | rejected), comment}].',
  EVIDENCE_SNAPSHOT  VARIANT NOT NULL COMMENT 'What was reviewed: title, type, date, reflection, file IDs and claimed KSBs, since the learner can edit the evidence afterwards.',
  CONSTRAINT PK_EVIDENCE_REVIEW PRIMARY KEY (REVIEW_ID),
  CONSTRAINT FK_EVIDENCE_REVIEW_EVIDENCE FOREIGN KEY (EVIDENCE_ID) REFERENCES CAPTURE_DB.BURROW.EVIDENCE (EVIDENCE_ID)
)
COMMENT = 'Burrow e-portfolio: the full history of reviews, one row per review. Append-only: never updated or deleted.';


-- ---------------------------------------------------------------------------
-- EVIDENCE_FILE: one row per uploaded file.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CAPTURE_DB.BURROW.EVIDENCE_FILE (
  FILE_ID            VARCHAR(36) DEFAULT UUID_STRING() NOT NULL,
  EVIDENCE_ID        VARCHAR(36) NOT NULL,
  STAGE_PATH         VARCHAR(500) NOT NULL COMMENT 'Path within @CAPTURE_DB.BURROW.EVIDENCE_FILES, built from IDs rather than the uploaded name, e.g. TESTL0001/<EVIDENCE_ID>/<FILE_ID>.pdf. Unique.',
  ORIGINAL_FILENAME  VARCHAR(255) NOT NULL COMMENT 'The name the file had on the uploader''s device, shown to users.',
  CONTENT_TYPE       VARCHAR(100) NOT NULL COMMENT 'MIME type, e.g. application/pdf, image/jpeg.',
  SIZE_BYTES         NUMBER(38,0) NOT NULL,
  CHECKSUM_MD5       VARCHAR(32) COMMENT 'MD5 of the uploaded file (as the stage''s directory table reports it), to show it hasn''t changed since.',
  UPLOADED_AT        TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
  UPLOADED_BY        VARCHAR(100) NOT NULL,
  REMOVED_AT         TIMESTAMP_LTZ COMMENT 'Set when a file is taken off a draft. The row and the staged file are both kept.',
  REMOVED_BY         VARCHAR(100),
  CONSTRAINT PK_EVIDENCE_FILE PRIMARY KEY (FILE_ID),
  CONSTRAINT UQ_EVIDENCE_FILE_STAGE_PATH UNIQUE (STAGE_PATH),
  CONSTRAINT FK_EVIDENCE_FILE_EVIDENCE FOREIGN KEY (EVIDENCE_ID) REFERENCES CAPTURE_DB.BURROW.EVIDENCE (EVIDENCE_ID)
)
COMMENT = 'Burrow e-portfolio: files attached to evidence, stored in the EVIDENCE_FILES stage. Never deleted - REMOVED_AT is set instead.';


-- ---------------------------------------------------------------------------
-- EVIDENCE_KSB: the KSBs each piece of evidence claims, with the current
-- decision on each. Past decisions are in EVIDENCE_REVIEW.KSB_DECISIONS.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CAPTURE_DB.BURROW.EVIDENCE_KSB (
  EVIDENCE_ID        VARCHAR(36) NOT NULL,
  ST_REFERENCE       VARCHAR(10) NOT NULL COMMENT 'Same as EVIDENCE.ST_REFERENCE, kept here so a claim joins straight to SKILLS.OCCUPATION.ST_REFERENCE.',
  KSB_TYPE           VARCHAR(1) NOT NULL COMMENT 'K | S | B',
  KSB_REFERENCE      VARCHAR(10) NOT NULL COMMENT 'e.g. K1, S3, B2 - as SKILLS.KSB.KSB_REFERENCE.',
  KSB_TEXT           VARCHAR COMMENT 'The KSB''s wording when it was claimed, since a new version of the standard can change it.',
  STANDARD_VERSION   VARCHAR(20) COMMENT 'The standard version the KSB text came from (SKILLS.OCCUPATION.VERSION), if known.',
  CLAIMED_AT         TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
  CLAIMED_BY         VARCHAR(100) NOT NULL,
  UNCLAIMED_AT       TIMESTAMP_LTZ COMMENT 'Set when the learner takes the claim off a draft, and cleared if they add it back.',
  UNCLAIMED_BY       VARCHAR(100),
  DECISION           VARCHAR(10) COMMENT 'Current assessor decision: NULL (not yet reviewed) | confirmed | rejected',
  DECISION_COMMENT   VARCHAR(1000) COMMENT 'Why, for this KSB specifically.',
  DECIDED_AT         TIMESTAMP_LTZ,
  DECIDED_BY         VARCHAR(20) COMMENT 'OFFICERREFNUMBER of the assessor.',
  DECIDED_IN_REVIEW  VARCHAR(36) COMMENT 'The EVIDENCE_REVIEW row that made the current decision.',
  CONSTRAINT PK_EVIDENCE_KSB PRIMARY KEY (EVIDENCE_ID, KSB_TYPE, KSB_REFERENCE),
  CONSTRAINT FK_EVIDENCE_KSB_EVIDENCE FOREIGN KEY (EVIDENCE_ID) REFERENCES CAPTURE_DB.BURROW.EVIDENCE (EVIDENCE_ID),
  CONSTRAINT FK_EVIDENCE_KSB_REVIEW FOREIGN KEY (DECIDED_IN_REVIEW) REFERENCES CAPTURE_DB.BURROW.EVIDENCE_REVIEW (REVIEW_ID)
)
COMMENT = 'Burrow e-portfolio: KSBs claimed by each piece of evidence, and the assessor''s current decision on each. Never deleted - UNCLAIMED_AT is set instead.';


-- ---------------------------------------------------------------------------
-- Make the review history append-only for the app. The schema's future
-- grants give ILR_APP_ROLE UPDATE on every new table, but reviews must only
-- ever be added, so take UPDATE back on this one. (SELECT and INSERT stay.)
-- ---------------------------------------------------------------------------
REVOKE UPDATE ON TABLE CAPTURE_DB.BURROW.EVIDENCE_REVIEW FROM ROLE ILR_APP_ROLE;


-- ---------------------------------------------------------------------------
-- Checks to run afterwards: ILR_APP_ROLE should have SELECT, INSERT and
-- UPDATE on EVIDENCE, EVIDENCE_FILE and EVIDENCE_KSB, only SELECT and
-- INSERT on EVIDENCE_REVIEW, and no DELETE anywhere.
-- ---------------------------------------------------------------------------
SHOW GRANTS ON TABLE CAPTURE_DB.BURROW.EVIDENCE;
SHOW GRANTS ON TABLE CAPTURE_DB.BURROW.EVIDENCE_REVIEW;
SHOW GRANTS ON TABLE CAPTURE_DB.BURROW.EVIDENCE_FILE;
SHOW GRANTS ON TABLE CAPTURE_DB.BURROW.EVIDENCE_KSB;


-- ---------------------------------------------------------------------------
-- For reference (not run): how the portfolio screen would work out a
-- learner's KSB progress. A KSB counts as achieved once an assessor has
-- confirmed it on evidence that has been signed off and not withdrawn.
-- ---------------------------------------------------------------------------
-- SELECT ek.KSB_TYPE, ek.KSB_REFERENCE, COUNT(*) AS CONFIRMED_BY
-- FROM CAPTURE_DB.BURROW.EVIDENCE e
-- JOIN CAPTURE_DB.BURROW.EVIDENCE_KSB ek ON ek.EVIDENCE_ID = e.EVIDENCE_ID
-- WHERE e.LEARNREFNUMBER = 'TESTL0001'
--   AND e.ST_REFERENCE = 'ST0072'
--   AND e.STATUS = 'signed_off'
--   AND ek.UNCLAIMED_AT IS NULL
--   AND ek.DECISION = 'confirmed'
-- GROUP BY ek.KSB_TYPE, ek.KSB_REFERENCE
