-- Progress reviews in CAPTURE_DB.ILR.
--
-- Run by hand as ACCOUNTADMIN in a Snowflake worksheet. Safe to run twice:
-- CREATE TABLE IF NOT EXISTS leaves an existing table alone, and GRANT does
-- nothing if the privileges are already there.
--
-- Reviews are part of a learner's official record, so the app can add and
-- update them but never delete them - the same rule as Burrow evidence.
-- ILR_APP_ROLE gets SELECT, INSERT and UPDATE only. The ILR schema's future
-- grants already give exactly those three on new tables, and the GRANT below
-- states them explicitly so the script doesn't depend on that.
--
-- Column names follow the ILR schema's style (no underscores, as in
-- OFFICERREFNUMBER). Snowflake records the keys but doesn't enforce them,
-- so the app checks the learner and officer exist before saving.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE capture_wh;

CREATE TABLE IF NOT EXISTS CAPTURE_DB.ILR.PROGRESS_REVIEW (
  REVIEWID           VARCHAR(36) DEFAULT UUID_STRING() NOT NULL COMMENT 'Generated by the app with crypto.randomUUID(). UUID_STRING() is only a fallback.',
  LEARNREFNUMBER     VARCHAR(12) NOT NULL COMMENT 'The learner, as LEARNER.LEARNREFNUMBER.',
  OFFICERREFNUMBER   VARCHAR(20) NOT NULL COMMENT 'The officer who held the review, as OFFICER.OFFICERREFNUMBER.',
  REVIEWDATE         DATE NOT NULL COMMENT 'The date the review took place.',
  EMPLOYERATTENDED   BOOLEAN NOT NULL COMMENT 'Whether the employer took part in the review.',
  SUMMARY            VARCHAR(1000) NOT NULL COMMENT 'A short summary of the review.',
  CREATEDAT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL COMMENT 'When the review was recorded in Warren.',
  UPDATEDAT          TIMESTAMP_LTZ COMMENT 'When the record was last corrected, if ever.',
  CONSTRAINT PK_PROGRESS_REVIEW PRIMARY KEY (REVIEWID),
  CONSTRAINT FK_PROGRESS_REVIEW_LEARNER FOREIGN KEY (LEARNREFNUMBER) REFERENCES CAPTURE_DB.ILR.LEARNER (LEARNREFNUMBER),
  CONSTRAINT FK_PROGRESS_REVIEW_OFFICER FOREIGN KEY (OFFICERREFNUMBER) REFERENCES CAPTURE_DB.ILR.OFFICER (OFFICERREFNUMBER)
)
COMMENT = 'Progress reviews held with each learner. Part of the official record - added and corrected, never deleted.';

GRANT SELECT, INSERT, UPDATE ON TABLE CAPTURE_DB.ILR.PROGRESS_REVIEW TO ROLE ILR_APP_ROLE;

-- Check afterwards: ILR_APP_ROLE should have SELECT, INSERT and UPDATE, and no DELETE.
SHOW GRANTS ON TABLE CAPTURE_DB.ILR.PROGRESS_REVIEW;
