-- Skills England, file 4 checks: run these one at a time, after Run All on
-- sql/skills_04_option_references.sql, as ACCOUNTADMIN.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE capture_wh;

-- 1. The primary keys. Expected: STANDARD_DUTY_OPTION ST_REFERENCE,
--    VERSION, DUTY_REFERENCE, OPTION_REFERENCE; STANDARD_OPTION
--    ST_REFERENCE, VERSION, OPTION_REFERENCE.
SHOW PRIMARY KEYS IN SCHEMA CAPTURE_DB.SKILLS
  ->> SELECT "table_name", LISTAGG("column_name", ', ') WITHIN GROUP (ORDER BY "key_sequence") AS KEY_COLUMNS
      FROM $1 WHERE "table_name" IN ('STANDARD_OPTION', 'STANDARD_DUTY_OPTION') GROUP BY "table_name" ORDER BY 1;

-- 2. ST0363 1.0 keeps both options. Expected: 4 rows, O1 Compliance, O2
--    Compliance and risk (for smaller organisations), O3 Financial crime,
--    O4 Specialist risk; O1 and O2 with the same OPTION_ID.
SELECT OPTION_REFERENCE, OPTION_ID, TITLE FROM CAPTURE_DB.SKILLS.STANDARD_OPTION
WHERE ST_REFERENCE = 'ST0363' AND VERSION = '1.0' ORDER BY SORT_ORDER;

-- 3. Every option and duty link has a reference, and each duty link points
--    at its option. Expected: 0 in every column.
SELECT
  (SELECT COUNT(*) FROM CAPTURE_DB.SKILLS.STANDARD_OPTION WHERE OPTION_REFERENCE IS NULL OR OPTION_REFERENCE <> 'O' || SORT_ORDER) AS OPTIONS_WRONG,
  (SELECT COUNT(*) FROM CAPTURE_DB.SKILLS.STANDARD_DUTY_OPTION d
     LEFT JOIN CAPTURE_DB.SKILLS.STANDARD_OPTION o
       ON o.ST_REFERENCE = d.ST_REFERENCE AND o.VERSION = d.VERSION AND o.OPTION_REFERENCE = d.OPTION_REFERENCE
     WHERE o.OPTION_ID IS NULL OR o.OPTION_ID <> d.OPTION_ID) AS DUTY_LINKS_WRONG;

-- 4. No SKILLS table has two rows for one primary key (Snowflake doesn't
--    enforce them; npm run check:test-flags checks the same). Expected: 0
--    in every column.
SELECT
  (SELECT COUNT(*) FROM (SELECT 1 FROM CAPTURE_DB.SKILLS.STANDARD_VERSION GROUP BY ST_REFERENCE, VERSION HAVING COUNT(*) > 1)) AS STANDARD_VERSION,
  (SELECT COUNT(*) FROM (SELECT 1 FROM CAPTURE_DB.SKILLS.STANDARD_KSB GROUP BY ST_REFERENCE, VERSION, KSB_TYPE, KSB_REFERENCE HAVING COUNT(*) > 1)) AS STANDARD_KSB,
  (SELECT COUNT(*) FROM (SELECT 1 FROM CAPTURE_DB.SKILLS.STANDARD_DUTY GROUP BY ST_REFERENCE, VERSION, DUTY_REFERENCE HAVING COUNT(*) > 1)) AS STANDARD_DUTY,
  (SELECT COUNT(*) FROM (SELECT 1 FROM CAPTURE_DB.SKILLS.STANDARD_DUTY_KSB GROUP BY ST_REFERENCE, VERSION, DUTY_REFERENCE, KSB_TYPE, KSB_REFERENCE HAVING COUNT(*) > 1)) AS STANDARD_DUTY_KSB,
  (SELECT COUNT(*) FROM (SELECT 1 FROM CAPTURE_DB.SKILLS.STANDARD_OPTION GROUP BY ST_REFERENCE, VERSION, OPTION_REFERENCE HAVING COUNT(*) > 1)) AS STANDARD_OPTION,
  (SELECT COUNT(*) FROM (SELECT 1 FROM CAPTURE_DB.SKILLS.STANDARD_DUTY_OPTION GROUP BY ST_REFERENCE, VERSION, DUTY_REFERENCE, OPTION_REFERENCE HAVING COUNT(*) > 1)) AS STANDARD_DUTY_OPTION,
  (SELECT COUNT(*) FROM (SELECT 1 FROM CAPTURE_DB.SKILLS.OCCUPATION_PROFILE GROUP BY OCCUPATION_CODE HAVING COUNT(*) > 1)) AS OCCUPATION_PROFILE,
  (SELECT COUNT(*) FROM (SELECT 1 FROM CAPTURE_DB.SKILLS.OCCUPATION_SOC GROUP BY OCCUPATION_CODE, SOC_VERSION, SOC_KEY HAVING COUNT(*) > 1)) AS OCCUPATION_SOC,
  (SELECT COUNT(*) FROM (SELECT 1 FROM CAPTURE_DB.SKILLS.OCCUPATION_TERM GROUP BY OCCUPATION_CODE, KIND, TERM HAVING COUNT(*) > 1)) AS OCCUPATION_TERM,
  (SELECT COUNT(*) FROM (SELECT 1 FROM CAPTURE_DB.SKILLS.SKILLS_IMPORT_RUN GROUP BY RUNID HAVING COUNT(*) > 1)) AS SKILLS_IMPORT_RUN;

-- 5. The app's role on the three tables is unchanged. Expected: INSERT,
--    SELECT, UPDATE for each (no DELETE).
SELECT TABLE_NAME, LISTAGG(PRIVILEGE_TYPE, ', ') WITHIN GROUP (ORDER BY PRIVILEGE_TYPE) AS PRIVILEGES
FROM CAPTURE_DB.INFORMATION_SCHEMA.TABLE_PRIVILEGES
WHERE GRANTEE = 'ILR_APP_ROLE' AND TABLE_SCHEMA = 'SKILLS' AND TABLE_NAME IN ('STANDARD_OPTION', 'STANDARD_DUTY_OPTION', 'SKILLS_IMPORT_RUN')
GROUP BY TABLE_NAME ORDER BY TABLE_NAME;
