-- Skills England, file 1 checks: run these one at a time, after Run All on
-- sql/skills_01_tables.sql, as ACCOUNTADMIN.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE capture_wh;

-- 1. The old tables are renamed and owned by ACCOUNTADMIN. Expected: 7 rows
--    (DUTY_KSB_OLD, DUTY_OLD, KSB_OLD, OCCUPATION_OLD, SKILLS_IMPORT_RUN_OLD,
--    STANDARD_IMPORT_RUN_OLD, STANDARD_VERSION_OLD), each owned by
--    ACCOUNTADMIN.
SHOW TABLES IN SCHEMA CAPTURE_DB.SKILLS
  ->> SELECT "name", "owner", "rows" FROM $1 WHERE ENDSWITH("name", '_OLD') ORDER BY "name";

-- 2. No SKILLS table is owned by the app's role any more. Expected: 0.
SHOW TABLES IN SCHEMA CAPTURE_DB.SKILLS
  ->> SELECT COUNT(*) AS OWNED_BY_APP FROM $1 WHERE "owner" = 'ILR_APP_ROLE';

-- 3. The app's role can't create tables in SKILLS. Expected: USAGE only.
SHOW GRANTS ON SCHEMA CAPTURE_DB.SKILLS
  ->> SELECT "privilege" FROM $1 WHERE "grantee_name" = 'ILR_APP_ROLE' ORDER BY 1;

-- 4. The app's role on the new tables and views. Expected: RAW
--    SE_OCCUPATION and SE_STANDARD_VERSION INSERT only; every new SKILLS
--    table (10) INSERT, SELECT, UPDATE; the views KSB and OCCUPATION SELECT
--    only. No DELETE anywhere, nothing on a *_OLD table.
SELECT TABLE_SCHEMA, TABLE_NAME, LISTAGG(PRIVILEGE_TYPE, ', ') WITHIN GROUP (ORDER BY PRIVILEGE_TYPE) AS PRIVILEGES
FROM CAPTURE_DB.INFORMATION_SCHEMA.TABLE_PRIVILEGES
WHERE GRANTEE = 'ILR_APP_ROLE' AND (TABLE_SCHEMA = 'SKILLS' OR (TABLE_SCHEMA = 'RAW' AND STARTSWITH(TABLE_NAME, 'SE_')))
GROUP BY TABLE_SCHEMA, TABLE_NAME
ORDER BY TABLE_SCHEMA, TABLE_NAME;

-- 5. The old versions were copied. Expected: VERSIONS 2020 and
--    WITH_OTJ_MINIMUM 1095 in both rows, and DIFFERENT 0.
SELECT 'new' AS TABLE_, COUNT(*) AS VERSIONS, COUNT(MIN_OTJ_HOURS) AS WITH_OTJ_MINIMUM,
  (SELECT COUNT(*) FROM (
     SELECT ST_REFERENCE, VERSION, LARS_CODE, EARLIEST_START_DATE, LATEST_START_DATE, MIN_OTJ_HOURS FROM CAPTURE_DB.SKILLS.STANDARD_VERSION
     MINUS
     SELECT ST_REFERENCE, VERSION, LARS_CODE, EARLIEST_START_DATE, LATEST_START_DATE, MIN_OTJ_HOURS FROM CAPTURE_DB.SKILLS.STANDARD_VERSION_OLD)) AS DIFFERENT
FROM CAPTURE_DB.SKILLS.STANDARD_VERSION
UNION ALL
SELECT 'old', COUNT(*), COUNT(MIN_OTJ_HOURS), NULL FROM CAPTURE_DB.SKILLS.STANDARD_VERSION_OLD;

-- 6. The stand-in views work, and are empty like the old tables. Expected:
--    KSB_VIEW 0, OCCUPATION_VIEW 0.
SELECT (SELECT COUNT(*) FROM CAPTURE_DB.SKILLS.KSB) AS KSB_VIEW,
       (SELECT COUNT(*) FROM CAPTURE_DB.SKILLS.OCCUPATION) AS OCCUPATION_VIEW;

-- 7. The new tables are empty, ready for the first import. Expected: 0 in
--    every column.
SELECT
  (SELECT COUNT(*) FROM CAPTURE_DB.SKILLS.STANDARD_KSB) AS KSBS,
  (SELECT COUNT(*) FROM CAPTURE_DB.SKILLS.STANDARD_DUTY) AS DUTIES,
  (SELECT COUNT(*) FROM CAPTURE_DB.SKILLS.STANDARD_OPTION) AS OPTIONS,
  (SELECT COUNT(*) FROM CAPTURE_DB.SKILLS.OCCUPATION_PROFILE) AS OCCUPATIONS,
  (SELECT COUNT(*) FROM CAPTURE_DB.SKILLS.OCCUPATION_SOC) AS SOC_CODES,
  (SELECT COUNT(*) FROM CAPTURE_DB.SKILLS.SKILLS_IMPORT_RUN) AS RUNS;
