-- Resetting the test learners, file 1 of 2: TEST DATA ONLY. Takes a
-- snapshot of every test learner (ISTESTDATA = TRUE) and the records the
-- learner page can change, so sql/test_reset_02_reset.sql can put them back
-- after testing, with the QAR mix as it was.
--
-- Run by hand as ACCOUNTADMIN in a Snowflake worksheet, once, AFTER
-- sql/ilr_04_capture.sql (so the snapshot has the new columns) and before
-- testing the capture screens. Safe to run twice: a snapshot table that
-- already exists is left as it is, so running it again never overwrites the
-- snapshot with edited data. To take a new snapshot, drop the schema first
-- (DROP SCHEMA CAPTURE_DB.TEST_BASELINE) and run this again.
--
-- The snapshot lives in its own schema, CAPTURE_DB.TEST_BASELINE, owned by
-- ACCOUNTADMIN. The app's role (ILR_APP_ROLE) is given no access to it.
-- Only test rows are copied: each table is filtered on ISTESTDATA = TRUE,
-- and tables keyed by learner also on the learner being a test learner.
--
-- What's in it: ILR.LEARNER, LEARNING_DELIVERY, the 8 ILR record tables,
-- OFFICER_ASSIGNMENT and LEARNER_EMPLOYER, as they are when this is run.
-- On 28 September 2026 that was 116 test learners (all in ORG-T001 and
-- ORG-T002) and no real rows on any of them.
--
-- If a later SQL file adds a column to one of these tables, it must add it
-- to the snapshot table too, or the reset can't copy the rows back (it
-- stops and changes nothing).

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE capture_wh;

CREATE SCHEMA IF NOT EXISTS CAPTURE_DB.TEST_BASELINE
  COMMENT = 'TEST DATA ONLY: a snapshot of the test learners, for sql/test_reset_02_reset.sql. No access for the app.';

CREATE TABLE IF NOT EXISTS CAPTURE_DB.TEST_BASELINE.LEARNER AS
  SELECT * FROM CAPTURE_DB.ILR.LEARNER WHERE ISTESTDATA = TRUE;

CREATE TABLE IF NOT EXISTS CAPTURE_DB.TEST_BASELINE.LEARNING_DELIVERY AS
  SELECT * FROM CAPTURE_DB.ILR.LEARNING_DELIVERY
  WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.ILR.LEARNER WHERE ISTESTDATA = TRUE);

CREATE TABLE IF NOT EXISTS CAPTURE_DB.TEST_BASELINE.PRIOR_ATTAINMENT AS
  SELECT * FROM CAPTURE_DB.ILR.PRIOR_ATTAINMENT
  WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.ILR.LEARNER WHERE ISTESTDATA = TRUE);

CREATE TABLE IF NOT EXISTS CAPTURE_DB.TEST_BASELINE.LLDD_HEALTH_PROBLEM AS
  SELECT * FROM CAPTURE_DB.ILR.LLDD_HEALTH_PROBLEM
  WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.ILR.LEARNER WHERE ISTESTDATA = TRUE);

CREATE TABLE IF NOT EXISTS CAPTURE_DB.TEST_BASELINE.LEARNER_FAM AS
  SELECT * FROM CAPTURE_DB.ILR.LEARNER_FAM
  WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.ILR.LEARNER WHERE ISTESTDATA = TRUE);

CREATE TABLE IF NOT EXISTS CAPTURE_DB.TEST_BASELINE.EMPLOYMENT_STATUS AS
  SELECT * FROM CAPTURE_DB.ILR.EMPLOYMENT_STATUS
  WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.ILR.LEARNER WHERE ISTESTDATA = TRUE);

CREATE TABLE IF NOT EXISTS CAPTURE_DB.TEST_BASELINE.EMPLOYMENT_STATUS_MONITORING AS
  SELECT * FROM CAPTURE_DB.ILR.EMPLOYMENT_STATUS_MONITORING
  WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.ILR.LEARNER WHERE ISTESTDATA = TRUE);

CREATE TABLE IF NOT EXISTS CAPTURE_DB.TEST_BASELINE.LEARNING_DELIVERY_FAM AS
  SELECT * FROM CAPTURE_DB.ILR.LEARNING_DELIVERY_FAM
  WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.ILR.LEARNER WHERE ISTESTDATA = TRUE);

CREATE TABLE IF NOT EXISTS CAPTURE_DB.TEST_BASELINE.APP_FIN_RECORD AS
  SELECT * FROM CAPTURE_DB.ILR.APP_FIN_RECORD
  WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.ILR.LEARNER WHERE ISTESTDATA = TRUE);

CREATE TABLE IF NOT EXISTS CAPTURE_DB.TEST_BASELINE.HOURS_RECORD AS
  SELECT * FROM CAPTURE_DB.ILR.HOURS_RECORD
  WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.ILR.LEARNER WHERE ISTESTDATA = TRUE);

CREATE TABLE IF NOT EXISTS CAPTURE_DB.TEST_BASELINE.OFFICER_ASSIGNMENT AS
  SELECT * FROM CAPTURE_DB.ILR.OFFICER_ASSIGNMENT
  WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.ILR.LEARNER WHERE ISTESTDATA = TRUE);

CREATE TABLE IF NOT EXISTS CAPTURE_DB.TEST_BASELINE.LEARNER_EMPLOYER AS
  SELECT * FROM CAPTURE_DB.ILR.LEARNER_EMPLOYER
  WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.ILR.LEARNER WHERE ISTESTDATA = TRUE);

-- ---------------------------------------------------------------------------
-- Checks
-- ---------------------------------------------------------------------------

-- 1. What the snapshot holds. Expected, if nothing has been changed since
--    28 September 2026: LEARNER 116, LEARNING_DELIVERY 288,
--    PRIOR_ATTAINMENT 116, LLDD_HEALTH_PROBLEM 25, LEARNER_FAM 0,
--    EMPLOYMENT_STATUS 116, EMPLOYMENT_STATUS_MONITORING 232,
--    LEARNING_DELIVERY_FAM 9, APP_FIN_RECORD 232, HOURS_RECORD 175,
--    OFFICER_ASSIGNMENT 235, LEARNER_EMPLOYER 97. And 0 in NOT_TEST.
SELECT 'LEARNER' AS TABLE_NAME, COUNT(*) AS ROWS_, COUNT_IF(NOT ISTESTDATA) AS NOT_TEST FROM CAPTURE_DB.TEST_BASELINE.LEARNER
UNION ALL SELECT 'LEARNING_DELIVERY', COUNT(*), COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.LEARNING_DELIVERY
UNION ALL SELECT 'PRIOR_ATTAINMENT', COUNT(*), COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.PRIOR_ATTAINMENT
UNION ALL SELECT 'LLDD_HEALTH_PROBLEM', COUNT(*), COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.LLDD_HEALTH_PROBLEM
UNION ALL SELECT 'LEARNER_FAM', COUNT(*), COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.LEARNER_FAM
UNION ALL SELECT 'EMPLOYMENT_STATUS', COUNT(*), COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.EMPLOYMENT_STATUS
UNION ALL SELECT 'EMPLOYMENT_STATUS_MONITORING', COUNT(*), COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.EMPLOYMENT_STATUS_MONITORING
UNION ALL SELECT 'LEARNING_DELIVERY_FAM', COUNT(*), COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.LEARNING_DELIVERY_FAM
UNION ALL SELECT 'APP_FIN_RECORD', COUNT(*), COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.APP_FIN_RECORD
UNION ALL SELECT 'HOURS_RECORD', COUNT(*), COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.HOURS_RECORD
UNION ALL SELECT 'OFFICER_ASSIGNMENT', COUNT(*), COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.OFFICER_ASSIGNMENT
UNION ALL SELECT 'LEARNER_EMPLOYER', COUNT(*), COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.LEARNER_EMPLOYER;

-- 2. The app's role can't see the snapshot. Expected: no rows.
SHOW GRANTS ON SCHEMA CAPTURE_DB.TEST_BASELINE;
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE "grantee_name" = 'ILR_APP_ROLE';
