-- Resetting the test learners, file 2 of 2: TEST DATA ONLY. Puts every test
-- learner back as they were in the snapshot (sql/test_reset_01_baseline.sql),
-- so the QAR mix and the ILR return are as they were before testing.
--
-- Run by hand as ACCOUNTADMIN in a Snowflake worksheet, whenever the test
-- learners need resetting. Run the whole file: the reset is one
-- transaction, so if any step fails (for example a table has gained a
-- column the snapshot doesn't have) it stops, changes nothing, and says
-- why. Then run the checks below.
--
-- What it changes, test data only (every delete and insert is limited to
-- ISTESTDATA = TRUE rows of test learners):
--   ILR.LEARNER, LEARNING_DELIVERY, the 8 ILR record tables,
--   OFFICER_ASSIGNMENT and LEARNER_EMPLOYER: every test learner's rows are
--   replaced with the snapshot's. Corrections and removals made in the app
--   go, and records added in the app go.
--   Test learners added in the app after the snapshot go too, with their
--   rows in these tables. (Their Burrow evidence, if any, stays.)
--   ILR.RECORD_CHANGE: the history of test learners' changes is emptied,
--   since the changes it describes are undone.
--   ILR.EMPLOYER: the test employers are put back as in the snapshot
--   (sql/employers_02_own_copy.sql), and test employers added in the app go.
-- It never touches a row with ISTESTDATA = FALSE, organisations, users,
-- officers, LARS, Burrow, or the shared Companies House tables (RAW, EXT).

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE capture_wh;

EXECUTE IMMEDIATE $$
DECLARE
  real_rows INTEGER;
BEGIN
  -- Stop before changing anything if the snapshot holds anything but test
  -- data.
  real_rows := (SELECT COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.LEARNER)
       + (SELECT COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.LEARNING_DELIVERY)
       + (SELECT COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.PRIOR_ATTAINMENT)
       + (SELECT COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.LLDD_HEALTH_PROBLEM)
       + (SELECT COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.LEARNER_FAM)
       + (SELECT COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.EMPLOYMENT_STATUS)
       + (SELECT COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.EMPLOYMENT_STATUS_MONITORING)
       + (SELECT COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.LEARNING_DELIVERY_FAM)
       + (SELECT COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.APP_FIN_RECORD)
       + (SELECT COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.HOURS_RECORD)
       + (SELECT COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.OFFICER_ASSIGNMENT)
       + (SELECT COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.LEARNER_EMPLOYER)
       + (SELECT COUNT_IF(NOT ISTESTDATA) FROM CAPTURE_DB.TEST_BASELINE.EMPLOYER);
  IF (real_rows > 0) THEN
    RETURN 'Stopped: the snapshot has rows that are not test data. Nothing was changed.';
  END IF;

  -- Which learners are test learners, noted before the transaction starts
  -- (creating a table inside a transaction would commit it early).
  CREATE OR REPLACE TEMPORARY TABLE CAPTURE_DB.TEST_BASELINE.RESET_TEST_LEARNERS AS
    SELECT LEARNREFNUMBER FROM CAPTURE_DB.ILR.LEARNER WHERE ISTESTDATA = TRUE;

  BEGIN TRANSACTION;

  -- The test learners' records, then the learners themselves.

  DELETE FROM CAPTURE_DB.ILR.LEARNING_DELIVERY WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.TEST_BASELINE.RESET_TEST_LEARNERS);
  DELETE FROM CAPTURE_DB.ILR.PRIOR_ATTAINMENT WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.TEST_BASELINE.RESET_TEST_LEARNERS);
  DELETE FROM CAPTURE_DB.ILR.LLDD_HEALTH_PROBLEM WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.TEST_BASELINE.RESET_TEST_LEARNERS);
  DELETE FROM CAPTURE_DB.ILR.LEARNER_FAM WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.TEST_BASELINE.RESET_TEST_LEARNERS);
  DELETE FROM CAPTURE_DB.ILR.EMPLOYMENT_STATUS WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.TEST_BASELINE.RESET_TEST_LEARNERS);
  DELETE FROM CAPTURE_DB.ILR.EMPLOYMENT_STATUS_MONITORING WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.TEST_BASELINE.RESET_TEST_LEARNERS);
  DELETE FROM CAPTURE_DB.ILR.LEARNING_DELIVERY_FAM WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.TEST_BASELINE.RESET_TEST_LEARNERS);
  DELETE FROM CAPTURE_DB.ILR.APP_FIN_RECORD WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.TEST_BASELINE.RESET_TEST_LEARNERS);
  DELETE FROM CAPTURE_DB.ILR.HOURS_RECORD WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.TEST_BASELINE.RESET_TEST_LEARNERS);
  DELETE FROM CAPTURE_DB.ILR.OFFICER_ASSIGNMENT WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.TEST_BASELINE.RESET_TEST_LEARNERS);
  DELETE FROM CAPTURE_DB.ILR.LEARNER_EMPLOYER WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.TEST_BASELINE.RESET_TEST_LEARNERS);
  DELETE FROM CAPTURE_DB.ILR.RECORD_CHANGE WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.TEST_BASELINE.RESET_TEST_LEARNERS);
  DELETE FROM CAPTURE_DB.ILR.LEARNER WHERE ISTESTDATA = TRUE AND LEARNREFNUMBER IN (SELECT LEARNREFNUMBER FROM CAPTURE_DB.TEST_BASELINE.RESET_TEST_LEARNERS);

  -- Back from the snapshot (test rows only, again).
  INSERT INTO CAPTURE_DB.ILR.LEARNER SELECT * FROM CAPTURE_DB.TEST_BASELINE.LEARNER WHERE ISTESTDATA = TRUE;
  INSERT INTO CAPTURE_DB.ILR.LEARNING_DELIVERY SELECT * FROM CAPTURE_DB.TEST_BASELINE.LEARNING_DELIVERY WHERE ISTESTDATA = TRUE;
  INSERT INTO CAPTURE_DB.ILR.PRIOR_ATTAINMENT SELECT * FROM CAPTURE_DB.TEST_BASELINE.PRIOR_ATTAINMENT WHERE ISTESTDATA = TRUE;
  INSERT INTO CAPTURE_DB.ILR.LLDD_HEALTH_PROBLEM SELECT * FROM CAPTURE_DB.TEST_BASELINE.LLDD_HEALTH_PROBLEM WHERE ISTESTDATA = TRUE;
  INSERT INTO CAPTURE_DB.ILR.LEARNER_FAM SELECT * FROM CAPTURE_DB.TEST_BASELINE.LEARNER_FAM WHERE ISTESTDATA = TRUE;
  INSERT INTO CAPTURE_DB.ILR.EMPLOYMENT_STATUS SELECT * FROM CAPTURE_DB.TEST_BASELINE.EMPLOYMENT_STATUS WHERE ISTESTDATA = TRUE;
  INSERT INTO CAPTURE_DB.ILR.EMPLOYMENT_STATUS_MONITORING SELECT * FROM CAPTURE_DB.TEST_BASELINE.EMPLOYMENT_STATUS_MONITORING WHERE ISTESTDATA = TRUE;
  INSERT INTO CAPTURE_DB.ILR.LEARNING_DELIVERY_FAM SELECT * FROM CAPTURE_DB.TEST_BASELINE.LEARNING_DELIVERY_FAM WHERE ISTESTDATA = TRUE;
  INSERT INTO CAPTURE_DB.ILR.APP_FIN_RECORD SELECT * FROM CAPTURE_DB.TEST_BASELINE.APP_FIN_RECORD WHERE ISTESTDATA = TRUE;
  INSERT INTO CAPTURE_DB.ILR.HOURS_RECORD SELECT * FROM CAPTURE_DB.TEST_BASELINE.HOURS_RECORD WHERE ISTESTDATA = TRUE;
  INSERT INTO CAPTURE_DB.ILR.OFFICER_ASSIGNMENT SELECT * FROM CAPTURE_DB.TEST_BASELINE.OFFICER_ASSIGNMENT WHERE ISTESTDATA = TRUE;
  INSERT INTO CAPTURE_DB.ILR.LEARNER_EMPLOYER SELECT * FROM CAPTURE_DB.TEST_BASELINE.LEARNER_EMPLOYER WHERE ISTESTDATA = TRUE;

  -- The test employers.
  DELETE FROM CAPTURE_DB.ILR.EMPLOYER WHERE ISTESTDATA = TRUE;
  INSERT INTO CAPTURE_DB.ILR.EMPLOYER SELECT * FROM CAPTURE_DB.TEST_BASELINE.EMPLOYER WHERE ISTESTDATA = TRUE;

  COMMIT;
  RETURN 'Reset: the test learners are back as they were in the snapshot. Run the checks below.';
EXCEPTION
  WHEN OTHER THEN
    ROLLBACK;
    RETURN 'Stopped and changed nothing: ' || SQLERRM;
END;
$$;

-- ---------------------------------------------------------------------------
-- Checks
-- ---------------------------------------------------------------------------

-- 1. Every table matches the snapshot. Expected: 0 in both columns on
--    every row (rows only in the live table, rows only in the snapshot).
SELECT 'LEARNER' AS TABLE_NAME,
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.ILR.LEARNER WHERE ISTESTDATA = TRUE MINUS SELECT * FROM CAPTURE_DB.TEST_BASELINE.LEARNER)) AS ONLY_LIVE,
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.TEST_BASELINE.LEARNER MINUS SELECT * FROM CAPTURE_DB.ILR.LEARNER WHERE ISTESTDATA = TRUE)) AS ONLY_SNAPSHOT
UNION ALL SELECT 'LEARNING_DELIVERY',
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.ILR.LEARNING_DELIVERY WHERE ISTESTDATA = TRUE MINUS SELECT * FROM CAPTURE_DB.TEST_BASELINE.LEARNING_DELIVERY)),
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.TEST_BASELINE.LEARNING_DELIVERY MINUS SELECT * FROM CAPTURE_DB.ILR.LEARNING_DELIVERY WHERE ISTESTDATA = TRUE))
UNION ALL SELECT 'PRIOR_ATTAINMENT',
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.ILR.PRIOR_ATTAINMENT WHERE ISTESTDATA = TRUE MINUS SELECT * FROM CAPTURE_DB.TEST_BASELINE.PRIOR_ATTAINMENT)),
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.TEST_BASELINE.PRIOR_ATTAINMENT MINUS SELECT * FROM CAPTURE_DB.ILR.PRIOR_ATTAINMENT WHERE ISTESTDATA = TRUE))
UNION ALL SELECT 'LLDD_HEALTH_PROBLEM',
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.ILR.LLDD_HEALTH_PROBLEM WHERE ISTESTDATA = TRUE MINUS SELECT * FROM CAPTURE_DB.TEST_BASELINE.LLDD_HEALTH_PROBLEM)),
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.TEST_BASELINE.LLDD_HEALTH_PROBLEM MINUS SELECT * FROM CAPTURE_DB.ILR.LLDD_HEALTH_PROBLEM WHERE ISTESTDATA = TRUE))
UNION ALL SELECT 'LEARNER_FAM',
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.ILR.LEARNER_FAM WHERE ISTESTDATA = TRUE MINUS SELECT * FROM CAPTURE_DB.TEST_BASELINE.LEARNER_FAM)),
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.TEST_BASELINE.LEARNER_FAM MINUS SELECT * FROM CAPTURE_DB.ILR.LEARNER_FAM WHERE ISTESTDATA = TRUE))
UNION ALL SELECT 'EMPLOYMENT_STATUS',
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.ILR.EMPLOYMENT_STATUS WHERE ISTESTDATA = TRUE MINUS SELECT * FROM CAPTURE_DB.TEST_BASELINE.EMPLOYMENT_STATUS)),
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.TEST_BASELINE.EMPLOYMENT_STATUS MINUS SELECT * FROM CAPTURE_DB.ILR.EMPLOYMENT_STATUS WHERE ISTESTDATA = TRUE))
UNION ALL SELECT 'EMPLOYMENT_STATUS_MONITORING',
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.ILR.EMPLOYMENT_STATUS_MONITORING WHERE ISTESTDATA = TRUE MINUS SELECT * FROM CAPTURE_DB.TEST_BASELINE.EMPLOYMENT_STATUS_MONITORING)),
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.TEST_BASELINE.EMPLOYMENT_STATUS_MONITORING MINUS SELECT * FROM CAPTURE_DB.ILR.EMPLOYMENT_STATUS_MONITORING WHERE ISTESTDATA = TRUE))
UNION ALL SELECT 'LEARNING_DELIVERY_FAM',
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.ILR.LEARNING_DELIVERY_FAM WHERE ISTESTDATA = TRUE MINUS SELECT * FROM CAPTURE_DB.TEST_BASELINE.LEARNING_DELIVERY_FAM)),
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.TEST_BASELINE.LEARNING_DELIVERY_FAM MINUS SELECT * FROM CAPTURE_DB.ILR.LEARNING_DELIVERY_FAM WHERE ISTESTDATA = TRUE))
UNION ALL SELECT 'APP_FIN_RECORD',
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.ILR.APP_FIN_RECORD WHERE ISTESTDATA = TRUE MINUS SELECT * FROM CAPTURE_DB.TEST_BASELINE.APP_FIN_RECORD)),
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.TEST_BASELINE.APP_FIN_RECORD MINUS SELECT * FROM CAPTURE_DB.ILR.APP_FIN_RECORD WHERE ISTESTDATA = TRUE))
UNION ALL SELECT 'HOURS_RECORD',
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.ILR.HOURS_RECORD WHERE ISTESTDATA = TRUE MINUS SELECT * FROM CAPTURE_DB.TEST_BASELINE.HOURS_RECORD)),
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.TEST_BASELINE.HOURS_RECORD MINUS SELECT * FROM CAPTURE_DB.ILR.HOURS_RECORD WHERE ISTESTDATA = TRUE))
UNION ALL SELECT 'OFFICER_ASSIGNMENT',
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.ILR.OFFICER_ASSIGNMENT WHERE ISTESTDATA = TRUE MINUS SELECT * FROM CAPTURE_DB.TEST_BASELINE.OFFICER_ASSIGNMENT)),
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.TEST_BASELINE.OFFICER_ASSIGNMENT MINUS SELECT * FROM CAPTURE_DB.ILR.OFFICER_ASSIGNMENT WHERE ISTESTDATA = TRUE))
UNION ALL SELECT 'LEARNER_EMPLOYER',
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.ILR.LEARNER_EMPLOYER WHERE ISTESTDATA = TRUE MINUS SELECT * FROM CAPTURE_DB.TEST_BASELINE.LEARNER_EMPLOYER)),
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.TEST_BASELINE.LEARNER_EMPLOYER MINUS SELECT * FROM CAPTURE_DB.ILR.LEARNER_EMPLOYER WHERE ISTESTDATA = TRUE))
UNION ALL SELECT 'EMPLOYER',
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.ILR.EMPLOYER WHERE ISTESTDATA = TRUE MINUS SELECT * FROM CAPTURE_DB.TEST_BASELINE.EMPLOYER)),
  (SELECT COUNT(*) FROM (SELECT * FROM CAPTURE_DB.TEST_BASELINE.EMPLOYER MINUS SELECT * FROM CAPTURE_DB.ILR.EMPLOYER WHERE ISTESTDATA = TRUE));

-- 2. The QAR mix, worked out as the Reports page does (server/reports.js).
--    Expected, as on 28 September 2026 (leavers, completers, achievers,
--    then achievement, retention and pass rates in %):
--    ORG-T001  2024 to 2025  21  16  14   66.7  76.2  87.5
--    ORG-T001  2025 to 2026  26  21  18   69.2  80.8  85.7
--    ORG-T002  2024 to 2025   4   3   2   50.0  75.0  66.7
--    ORG-T002  2025 to 2026   6   5   4   66.7  83.3  80.0
--    and in Warren, Reports -> QAR shows the same, with 7 (ORG-T001) and 1
--    (ORG-T002) learners in the "past their planned end date" warning.
WITH aims AS (
  SELECT l.ORGANISATIONID, ld.LEARNPLANENDDATE, ld.LEARNACTENDDATE, ld.ACHDATE, ld.COMPSTATUS, ld.OUTCOME, ld.WITHDRAWREASON,
         YEAR(DATEADD(month, -7, ld.LEARNPLANENDDATE)) AS PLANNED_END_YEAR,
         YEAR(DATEADD(month, -7, ld.LEARNACTENDDATE)) AS ACTUAL_END_YEAR,
         YEAR(DATEADD(month, -7, ld.ACHDATE)) AS ACHIEVEMENT_YEAR,
         DATEDIFF(day, ld.LEARNSTARTDATE, ld.LEARNPLANENDDATE) AS PLANNED_DAYS,
         DATEDIFF(day, ld.LEARNSTARTDATE, ld.LEARNACTENDDATE) AS ACTUAL_DAYS
  FROM CAPTURE_DB.ILR.LEARNING_DELIVERY ld
  JOIN CAPTURE_DB.ILR.LEARNER l ON l.LEARNREFNUMBER = ld.LEARNREFNUMBER
  WHERE ld.AIMTYPE = 1 AND ld.PROGTYPE IN (2, 3, 10, 20, 21, 22, 23, 25) AND l.ISTESTDATA = TRUE
    AND ld.REMOVEDAT IS NULL -- aims removed as entered in error don't count (sql/ilr_05_remove_aims.sql)
), flagged AS (
  SELECT *,
         GREATEST(COALESCE(ACHIEVEMENT_YEAR, 0), COALESCE(ACTUAL_END_YEAR, 0), PLANNED_END_YEAR) AS HYBRID_END_YEAR,
         COALESCE(COMPSTATUS IN (2, 3), FALSE) AS IS_LEAVER,
         COALESCE(COMPSTATUS = 2, FALSE) AS IS_COMPLETER,
         COALESCE(OUTCOME = 1, FALSE) AS IS_ACHIEVER,
         (COMPSTATUS = 3 AND COALESCE(OUTCOME, 0) <> 1
           AND ((PLANNED_DAYS >= 168 AND ACTUAL_DAYS < 42) OR (PLANNED_DAYS BETWEEN 14 AND 167 AND ACTUAL_DAYS < 14)))
         OR COMPSTATUS = 6 OR COALESCE(WITHDRAWREASON = 7, FALSE) AS IS_EXCLUDED
  FROM aims
)
SELECT ORGANISATIONID,
       HYBRID_END_YEAR || ' to ' || (HYBRID_END_YEAR + 1) AS ACADEMIC_YEAR,
       COUNT_IF(IS_LEAVER) AS LEAVERS,
       COUNT_IF(IS_COMPLETER) AS COMPLETERS,
       COUNT_IF(IS_ACHIEVER) AS ACHIEVERS,
       ROUND(100 * COUNT_IF(IS_ACHIEVER) / NULLIF(COUNT_IF(IS_LEAVER), 0), 1) AS ACHIEVEMENT_RATE,
       ROUND(100 * COUNT_IF(IS_COMPLETER) / NULLIF(COUNT_IF(IS_LEAVER), 0), 1) AS RETENTION_RATE,
       ROUND(100 * COUNT_IF(IS_ACHIEVER) / NULLIF(COUNT_IF(IS_COMPLETER), 0), 1) AS PASS_RATE
FROM flagged
WHERE NOT IS_EXCLUDED AND HYBRID_END_YEAR IN (2024, 2025)
GROUP BY ORGANISATIONID, HYBRID_END_YEAR
ORDER BY ORGANISATIONID, HYBRID_END_YEAR;

-- 3. Every row carries its learner's ISTESTDATA, so the reset found all of
--    a test learner's rows (a row added with the wrong flag would be left
--    behind, and check 1 wouldn't see it, since it only compares test rows).
--    ILR.LEARNER and ILR.EMPLOYER are compared with their organisation.
--    Expected: 0 in DIFFERENT and NO_LEARNER on every row (for LEARNER and
--    EMPLOYER, NO_LEARNER counts rows with no organisation). The app checks
--    the same with npm run check:test-flags.
SELECT 'LEARNER' AS TABLE_NAME, COUNT(*) AS ROWS_,
       COALESCE(COUNT_IF(l.ISTESTDATA IS DISTINCT FROM o.ISTESTDATA), 0) AS DIFFERENT,
       COALESCE(COUNT_IF(o.ORGANISATIONID IS NULL), 0) AS NO_LEARNER
FROM CAPTURE_DB.ILR.LEARNER l
LEFT JOIN CAPTURE_DB.ACCESS.ORGANISATION o ON o.ORGANISATIONID = l.ORGANISATIONID
UNION ALL
SELECT 'LEARNING_DELIVERY', COUNT(*),
       COALESCE(COUNT_IF(t.ISTESTDATA IS DISTINCT FROM l.ISTESTDATA), 0), COALESCE(COUNT_IF(l.LEARNREFNUMBER IS NULL), 0)
FROM CAPTURE_DB.ILR.LEARNING_DELIVERY t LEFT JOIN CAPTURE_DB.ILR.LEARNER l ON l.LEARNREFNUMBER = t.LEARNREFNUMBER
UNION ALL
SELECT 'PRIOR_ATTAINMENT', COUNT(*),
       COALESCE(COUNT_IF(t.ISTESTDATA IS DISTINCT FROM l.ISTESTDATA), 0), COALESCE(COUNT_IF(l.LEARNREFNUMBER IS NULL), 0)
FROM CAPTURE_DB.ILR.PRIOR_ATTAINMENT t LEFT JOIN CAPTURE_DB.ILR.LEARNER l ON l.LEARNREFNUMBER = t.LEARNREFNUMBER
UNION ALL
SELECT 'LLDD_HEALTH_PROBLEM', COUNT(*),
       COALESCE(COUNT_IF(t.ISTESTDATA IS DISTINCT FROM l.ISTESTDATA), 0), COALESCE(COUNT_IF(l.LEARNREFNUMBER IS NULL), 0)
FROM CAPTURE_DB.ILR.LLDD_HEALTH_PROBLEM t LEFT JOIN CAPTURE_DB.ILR.LEARNER l ON l.LEARNREFNUMBER = t.LEARNREFNUMBER
UNION ALL
SELECT 'LEARNER_FAM', COUNT(*),
       COALESCE(COUNT_IF(t.ISTESTDATA IS DISTINCT FROM l.ISTESTDATA), 0), COALESCE(COUNT_IF(l.LEARNREFNUMBER IS NULL), 0)
FROM CAPTURE_DB.ILR.LEARNER_FAM t LEFT JOIN CAPTURE_DB.ILR.LEARNER l ON l.LEARNREFNUMBER = t.LEARNREFNUMBER
UNION ALL
SELECT 'EMPLOYMENT_STATUS', COUNT(*),
       COALESCE(COUNT_IF(t.ISTESTDATA IS DISTINCT FROM l.ISTESTDATA), 0), COALESCE(COUNT_IF(l.LEARNREFNUMBER IS NULL), 0)
FROM CAPTURE_DB.ILR.EMPLOYMENT_STATUS t LEFT JOIN CAPTURE_DB.ILR.LEARNER l ON l.LEARNREFNUMBER = t.LEARNREFNUMBER
UNION ALL
SELECT 'EMPLOYMENT_STATUS_MONITORING', COUNT(*),
       COALESCE(COUNT_IF(t.ISTESTDATA IS DISTINCT FROM l.ISTESTDATA), 0), COALESCE(COUNT_IF(l.LEARNREFNUMBER IS NULL), 0)
FROM CAPTURE_DB.ILR.EMPLOYMENT_STATUS_MONITORING t LEFT JOIN CAPTURE_DB.ILR.LEARNER l ON l.LEARNREFNUMBER = t.LEARNREFNUMBER
UNION ALL
SELECT 'LEARNING_DELIVERY_FAM', COUNT(*),
       COALESCE(COUNT_IF(t.ISTESTDATA IS DISTINCT FROM l.ISTESTDATA), 0), COALESCE(COUNT_IF(l.LEARNREFNUMBER IS NULL), 0)
FROM CAPTURE_DB.ILR.LEARNING_DELIVERY_FAM t LEFT JOIN CAPTURE_DB.ILR.LEARNER l ON l.LEARNREFNUMBER = t.LEARNREFNUMBER
UNION ALL
SELECT 'APP_FIN_RECORD', COUNT(*),
       COALESCE(COUNT_IF(t.ISTESTDATA IS DISTINCT FROM l.ISTESTDATA), 0), COALESCE(COUNT_IF(l.LEARNREFNUMBER IS NULL), 0)
FROM CAPTURE_DB.ILR.APP_FIN_RECORD t LEFT JOIN CAPTURE_DB.ILR.LEARNER l ON l.LEARNREFNUMBER = t.LEARNREFNUMBER
UNION ALL
SELECT 'HOURS_RECORD', COUNT(*),
       COALESCE(COUNT_IF(t.ISTESTDATA IS DISTINCT FROM l.ISTESTDATA), 0), COALESCE(COUNT_IF(l.LEARNREFNUMBER IS NULL), 0)
FROM CAPTURE_DB.ILR.HOURS_RECORD t LEFT JOIN CAPTURE_DB.ILR.LEARNER l ON l.LEARNREFNUMBER = t.LEARNREFNUMBER
UNION ALL
SELECT 'OFFICER_ASSIGNMENT', COUNT(*),
       COALESCE(COUNT_IF(t.ISTESTDATA IS DISTINCT FROM l.ISTESTDATA), 0), COALESCE(COUNT_IF(l.LEARNREFNUMBER IS NULL), 0)
FROM CAPTURE_DB.ILR.OFFICER_ASSIGNMENT t LEFT JOIN CAPTURE_DB.ILR.LEARNER l ON l.LEARNREFNUMBER = t.LEARNREFNUMBER
UNION ALL
SELECT 'LEARNER_EMPLOYER', COUNT(*),
       COALESCE(COUNT_IF(t.ISTESTDATA IS DISTINCT FROM l.ISTESTDATA), 0), COALESCE(COUNT_IF(l.LEARNREFNUMBER IS NULL), 0)
FROM CAPTURE_DB.ILR.LEARNER_EMPLOYER t LEFT JOIN CAPTURE_DB.ILR.LEARNER l ON l.LEARNREFNUMBER = t.LEARNREFNUMBER
UNION ALL
SELECT 'RECORD_CHANGE', COUNT(*),
       COALESCE(COUNT_IF(t.ISTESTDATA IS DISTINCT FROM l.ISTESTDATA), 0), COALESCE(COUNT_IF(l.LEARNREFNUMBER IS NULL), 0)
FROM CAPTURE_DB.ILR.RECORD_CHANGE t LEFT JOIN CAPTURE_DB.ILR.LEARNER l ON l.LEARNREFNUMBER = t.LEARNREFNUMBER
UNION ALL
SELECT 'EMPLOYER', COUNT(*),
       COALESCE(COUNT_IF(e.ISTESTDATA IS DISTINCT FROM o.ISTESTDATA), 0), COALESCE(COUNT_IF(o.ORGANISATIONID IS NULL), 0)
FROM CAPTURE_DB.ILR.EMPLOYER e LEFT JOIN CAPTURE_DB.ACCESS.ORGANISATION o ON o.ORGANISATIONID = e.ORGANISATIONID;

-- 4. Every employer ID points at an employer that exists (the reset puts
--    the test employers back, and removes ones added while testing), and at
--    one in the same organisation as the row. Expected: 0 in NO_EMPLOYER
--    and OTHER_ORGANISATION on every row, and 0 on the last row, which
--    counts tables with an EMPLOYERID column this check doesn't cover (add
--    them here and in npm run check:test-flags). The app checks the same
--    with npm run check:test-flags.
SELECT 'ILR.LEARNER_EMPLOYER' AS TABLE_NAME, COUNT(*) AS ROWS_,
       COALESCE(COUNT_IF(e.EMPLOYERID IS NULL), 0) AS NO_EMPLOYER,
       COALESCE(COUNT_IF(e.ORGANISATIONID IS DISTINCT FROM l.ORGANISATIONID AND e.EMPLOYERID IS NOT NULL), 0) AS OTHER_ORGANISATION
FROM CAPTURE_DB.ILR.LEARNER_EMPLOYER t
LEFT JOIN CAPTURE_DB.ILR.EMPLOYER e ON e.EMPLOYERID = t.EMPLOYERID
LEFT JOIN CAPTURE_DB.ILR.LEARNER l ON l.LEARNREFNUMBER = t.LEARNREFNUMBER
UNION ALL
SELECT 'ILR.EMPLOYMENT_STATUS', COUNT(*),
       COALESCE(COUNT_IF(e.EMPLOYERID IS NULL), 0),
       COALESCE(COUNT_IF(e.ORGANISATIONID IS DISTINCT FROM l.ORGANISATIONID AND e.EMPLOYERID IS NOT NULL), 0)
FROM CAPTURE_DB.ILR.EMPLOYMENT_STATUS t
LEFT JOIN CAPTURE_DB.ILR.EMPLOYER e ON e.EMPLOYERID = t.EMPLOYERID
LEFT JOIN CAPTURE_DB.ILR.LEARNER l ON l.LEARNREFNUMBER = t.LEARNREFNUMBER
WHERE t.EMPLOYERID IS NOT NULL
UNION ALL
SELECT 'ACCESS.APP_USER', COUNT(*),
       COALESCE(COUNT_IF(e.EMPLOYERID IS NULL), 0),
       COALESCE(COUNT_IF(e.ORGANISATIONID IS DISTINCT FROM t.ORGANISATIONID AND e.EMPLOYERID IS NOT NULL), 0)
FROM CAPTURE_DB.ACCESS.APP_USER t
LEFT JOIN CAPTURE_DB.ILR.EMPLOYER e ON e.EMPLOYERID = t.EMPLOYERID
WHERE t.EMPLOYERID IS NOT NULL
UNION ALL
SELECT 'BURROW.WITNESS_CONFIRMATION', COUNT(*),
       COALESCE(COUNT_IF(e.EMPLOYERID IS NULL), 0),
       COALESCE(COUNT_IF(e.ORGANISATIONID IS DISTINCT FROM l.ORGANISATIONID AND e.EMPLOYERID IS NOT NULL), 0)
FROM CAPTURE_DB.BURROW.WITNESS_CONFIRMATION t
LEFT JOIN CAPTURE_DB.ILR.EMPLOYER e ON e.EMPLOYERID = t.EMPLOYERID
LEFT JOIN CAPTURE_DB.BURROW.EVIDENCE v ON v.EVIDENCE_ID = t.EVIDENCE_ID
LEFT JOIN CAPTURE_DB.ILR.LEARNER l ON l.LEARNREFNUMBER = v.LEARNREFNUMBER
UNION ALL
SELECT 'Tables with EMPLOYERID not checked here', COUNT(*), COUNT(*), 0
FROM CAPTURE_DB.INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EMPLOYERID' AND TABLE_SCHEMA <> 'TEST_BASELINE'
  AND TABLE_SCHEMA || '.' || TABLE_NAME NOT IN ('ILR.EMPLOYER', 'ILR.LEARNER_EMPLOYER', 'ILR.EMPLOYMENT_STATUS', 'ACCESS.APP_USER', 'BURROW.WITNESS_CONFIRMATION');
